import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./dashboard/_components/Header";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Header/> */}
        <div className="container mx-auto p-1 my-4">
          <Toaster/>
          {children}
        </div>
      </body>
    </html>
  );
}
